apiVersion: apps/v1
kind: Deployment
metadata:
  name: pospos-k8s
spec:
  replicas: 3  # 你想要的 Pod 副本數量
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website
        image: wdf332/waterfront:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: website-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007
  selector:
    app: website
